# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todo.proto',
  package='todo_app',
  syntax='proto3',
  serialized_pb=_b('\n\ntodo.proto\x12\x08todo_app\"\x14\n\x12GetAllTasksRequest\"\x8a\x01\n\x0fOperationStatus\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .todo_app.OperationStatus.Status\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\"5\n\x06Status\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"`\n\x12\x43reateTaskResponse\x12,\n\top_status\x18\x01 \x01(\x0b\x32\x19.todo_app.OperationStatus\x12\x1c\n\x04task\x18\x02 \x01(\x0b\x32\x0e.todo_app.Task\"B\n\x12\x44\x65leteTaskResponse\x12,\n\top_status\x18\x01 \x01(\x0b\x32\x19.todo_app.OperationStatus\"\x9f\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.todo_app.Task.TaskStatus\"K\n\nTaskStatus\x12\x17\n\x13UNKNOWN_TASK_STATUS\x10\x00\x12\x0c\n\x08\x43OMPLETE\x10\x01\x12\x0c\n\x08PROGRESS\x10\x02\x12\x08\n\x04TODO\x10\x03\"*\n\tTasksList\x12\x1d\n\x05tasks\x18\x01 \x03(\x0b\x32\x0e.todo_app.Task2\xf5\x01\n\x06Tasker\x12<\n\nCreateTask\x12\x0e.todo_app.Task\x1a\x1c.todo_app.CreateTaskResponse\"\x00\x12\x42\n\x0bGetAllTasks\x12\x1c.todo_app.GetAllTasksRequest\x1a\x13.todo_app.TasksList\"\x00\x12+\n\x07GetTask\x12\x0e.todo_app.Task\x1a\x0e.todo_app.Task\"\x00\x12<\n\nDeleteTask\x12\x0e.todo_app.Task\x1a\x1c.todo_app.DeleteTaskResponse\"\x00\x62\x06proto3')
)



_OPERATIONSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='todo_app.OperationStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=132,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONSTATUS_STATUS)

_TASK_TASKSTATUS = _descriptor.EnumDescriptor(
  name='TaskStatus',
  full_name='todo_app.Task.TaskStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TASK_STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TODO', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=438,
  serialized_end=513,
)
_sym_db.RegisterEnumDescriptor(_TASK_TASKSTATUS)


_GETALLTASKSREQUEST = _descriptor.Descriptor(
  name='GetAllTasksRequest',
  full_name='todo_app.GetAllTasksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_OPERATIONSTATUS = _descriptor.Descriptor(
  name='OperationStatus',
  full_name='todo_app.OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='todo_app.OperationStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='todo_app.OperationStatus.errors', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPERATIONSTATUS_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=185,
)


_CREATETASKRESPONSE = _descriptor.Descriptor(
  name='CreateTaskResponse',
  full_name='todo_app.CreateTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_status', full_name='todo_app.CreateTaskResponse.op_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task', full_name='todo_app.CreateTaskResponse.task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=283,
)


_DELETETASKRESPONSE = _descriptor.Descriptor(
  name='DeleteTaskResponse',
  full_name='todo_app.DeleteTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_status', full_name='todo_app.DeleteTaskResponse.op_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=351,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='todo_app.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo_app.Task.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='todo_app.Task.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='todo_app.Task.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_TASKSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=513,
)


_TASKSLIST = _descriptor.Descriptor(
  name='TasksList',
  full_name='todo_app.TasksList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='todo_app.TasksList.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=557,
)

_OPERATIONSTATUS.fields_by_name['status'].enum_type = _OPERATIONSTATUS_STATUS
_OPERATIONSTATUS_STATUS.containing_type = _OPERATIONSTATUS
_CREATETASKRESPONSE.fields_by_name['op_status'].message_type = _OPERATIONSTATUS
_CREATETASKRESPONSE.fields_by_name['task'].message_type = _TASK
_DELETETASKRESPONSE.fields_by_name['op_status'].message_type = _OPERATIONSTATUS
_TASK.fields_by_name['status'].enum_type = _TASK_TASKSTATUS
_TASK_TASKSTATUS.containing_type = _TASK
_TASKSLIST.fields_by_name['tasks'].message_type = _TASK
DESCRIPTOR.message_types_by_name['GetAllTasksRequest'] = _GETALLTASKSREQUEST
DESCRIPTOR.message_types_by_name['OperationStatus'] = _OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['CreateTaskResponse'] = _CREATETASKRESPONSE
DESCRIPTOR.message_types_by_name['DeleteTaskResponse'] = _DELETETASKRESPONSE
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['TasksList'] = _TASKSLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllTasksRequest = _reflection.GeneratedProtocolMessageType('GetAllTasksRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLTASKSREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_app.GetAllTasksRequest)
  ))
_sym_db.RegisterMessage(GetAllTasksRequest)

OperationStatus = _reflection.GeneratedProtocolMessageType('OperationStatus', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONSTATUS,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_app.OperationStatus)
  ))
_sym_db.RegisterMessage(OperationStatus)

CreateTaskResponse = _reflection.GeneratedProtocolMessageType('CreateTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATETASKRESPONSE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_app.CreateTaskResponse)
  ))
_sym_db.RegisterMessage(CreateTaskResponse)

DeleteTaskResponse = _reflection.GeneratedProtocolMessageType('DeleteTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETETASKRESPONSE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_app.DeleteTaskResponse)
  ))
_sym_db.RegisterMessage(DeleteTaskResponse)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_app.Task)
  ))
_sym_db.RegisterMessage(Task)

TasksList = _reflection.GeneratedProtocolMessageType('TasksList', (_message.Message,), dict(
  DESCRIPTOR = _TASKSLIST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_app.TasksList)
  ))
_sym_db.RegisterMessage(TasksList)



_TASKER = _descriptor.ServiceDescriptor(
  name='Tasker',
  full_name='todo_app.Tasker',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=560,
  serialized_end=805,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTask',
    full_name='todo_app.Tasker.CreateTask',
    index=0,
    containing_service=None,
    input_type=_TASK,
    output_type=_CREATETASKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllTasks',
    full_name='todo_app.Tasker.GetAllTasks',
    index=1,
    containing_service=None,
    input_type=_GETALLTASKSREQUEST,
    output_type=_TASKSLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='todo_app.Tasker.GetTask',
    index=2,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTask',
    full_name='todo_app.Tasker.DeleteTask',
    index=3,
    containing_service=None,
    input_type=_TASK,
    output_type=_DELETETASKRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKER)

DESCRIPTOR.services_by_name['Tasker'] = _TASKER

# @@protoc_insertion_point(module_scope)
