# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from generated_code import todo_pb2 as todo__pb2


class TaskerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTask = channel.unary_unary(
        '/todo_app.Tasker/CreateTask',
        request_serializer=todo__pb2.Task.SerializeToString,
        response_deserializer=todo__pb2.CreateTaskResponse.FromString,
        )
    self.GetAllTasks = channel.unary_unary(
        '/todo_app.Tasker/GetAllTasks',
        request_serializer=todo__pb2.GetAllTasksRequest.SerializeToString,
        response_deserializer=todo__pb2.TasksList.FromString,
        )
    self.GetTask = channel.unary_unary(
        '/todo_app.Tasker/GetTask',
        request_serializer=todo__pb2.Task.SerializeToString,
        response_deserializer=todo__pb2.Task.FromString,
        )
    self.DeleteTask = channel.unary_unary(
        '/todo_app.Tasker/DeleteTask',
        request_serializer=todo__pb2.Task.SerializeToString,
        response_deserializer=todo__pb2.DeleteTaskResponse.FromString,
        )


class TaskerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllTasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TaskerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTask': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTask,
          request_deserializer=todo__pb2.Task.FromString,
          response_serializer=todo__pb2.CreateTaskResponse.SerializeToString,
      ),
      'GetAllTasks': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllTasks,
          request_deserializer=todo__pb2.GetAllTasksRequest.FromString,
          response_serializer=todo__pb2.TasksList.SerializeToString,
      ),
      'GetTask': grpc.unary_unary_rpc_method_handler(
          servicer.GetTask,
          request_deserializer=todo__pb2.Task.FromString,
          response_serializer=todo__pb2.Task.SerializeToString,
      ),
      'DeleteTask': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTask,
          request_deserializer=todo__pb2.Task.FromString,
          response_serializer=todo__pb2.DeleteTaskResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo_app.Tasker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
